name: Add UUID to JSON files

on:
  push:
    paths:
      - '**.json'
  workflow_dispatch:

jobs:
  add-uuid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}  # 個人アクセストークンを使用
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install uuid
        
      - name: Add UUID to JSON files
        run: node .github/scripts/add-uuid-v1.js
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Add UUID to JSON files that don't have id"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: ${{ github.ref }}