name: Generate index.json

on:
  workflow_run:
    workflows: ["Add UUID to JSON files"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      target_directory:
        description: 'Target directory to process JSON files'
        required: true
        default: './public/v1/'

env:
  TARGET_DIR: ${{ github.event.inputs.target_directory || './public/v1/' }}

# 同時実行を制限して競合を防ぐ
concurrency:
  group: generate-index-${{ github.ref }}
  cancel-in-progress: false

jobs:
  generate-index:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0  # 完全な履歴を取得
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        
      - name: Generate ${{ secrets.PAT_TOKEN }}index.json
        run: node .github/scripts/generate-index.js
        env:
          TARGET_DIR: ${{ env.TARGET_DIR }}
        
      - name: Fetch latest changes before commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin
          git pull --no-rebase  # マージ戦略を使用
        
      - name: Commit changes
        run: |
          git add ${{ secrets.PAT_TOKEN }}index.json
          git diff --staged --quiet || git commit -m "Update index.json [skip ci]"
          
      - name: Push changes directly
        run: |
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
